spring.application.name=PetCare

#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#url database
spring.datasource.url = jdbc:mysql://localhost:3306/petCareManagement
#username which conect to database
spring.datasource.username=xpy
#password for the username
spring.datasource.password=1234
#set mybatis log it will show in console
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#open the map such as a_column -> aColumn
mybatis.configuration.map-underscore-to-camel-case=true
#
##??????????
#spring.servlet.multipart.max-file-size=10MB
#
##???????????
#spring.servlet.multipart.max-request-size=100MB
